// docs/src/examples/dropdown/dropdown.jsx
import { useState, useRef, useEffect } from "react"
import autoAnimate from "@moeindana/auto-animate"

const Dropdown = () => {
  const [show, setShow] = useState(false)
  const parent = useRef(null)

  useEffect(() => {
    parent.current && autoAnimate(parent.current)
  }, [parent])

  const reveal = () => setShow(!show)

  return (
    <div ref={parent}>
      <strong className="dropdown-label" onClick={reveal}>
        Click me to open!
      </strong>
      {show && <p className="dropdown-content">Lorum ipsum...</p>}
    </div>
  )
}

export default Dropdown

// docs/src/examples/dropdown/dropdown.vue
<script setup>
import { ref, onMounted } from "vue"
import autoAnimate from "@moeindana/auto-animate"

const dropdown = ref() // we need a DOM node
const show = ref(false)

onMounted(() => {
  autoAnimate(dropdown.value) // thats it!
})
</script>

<template>
  <div ref="dropdown" class="dropdown">
    <strong class="dropdown-label" @click="show = !show">
      Click me to open!
    </strong>
    <p class="dropdown-content" v-if="show">Lorum ipsum...</p>
  </div>
</template>
